version: '3.8'

services:
  flexpro:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "80:8080"  
    environment:
      ASPNETCORE_ENVIRONMENT: Production  
    restart: always  
    networks:
      - flexpro-network

networks:
  flexpro-network:
    external: true

