version: '3.8'

services:
  flexpro:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - flexpro-network
    restart: always


networks:
  flexpro-network:
    external: true