name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalar o .NET SDK (ajustado para .NET 9)
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'  # Versão do .NET 9.0

      # Restaurar dependências do Blazor
      - name: Restore dependencies
        run: dotnet restore

      # Limpar o diretório docs (caso existam arquivos antigos)
      - name: Clean docs directory
        run: rm -rf docs/*

      # Build do projeto Blazor e saída no diretório docs
      - name: Build Blazor project
        run: dotnet publish -c Release -o ./docs

      # Configurar o deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # A branch onde o site será publicado
          folder: ./docs/wwwroot 
          token: ${{ secrets.GH_TOKEN }}

      # Configura o cache (opcional) para acelerar os builds
      - name: Cache .NET
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-dotnetcore-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-dotnetcore-
